[project]
name = "connector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.84.0",
    "numpy>=2.2.6",
    "ruff>=0.11.12",
    "pydantic>=2.11.7",
]

[tool.setuptools]
package-dir = {"" = "src"}
