[project]
name = "connector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncio>=3.4.3",
    "numpy>=2.2.6",
    "ruff>=0.11.12",
    "whisper-live>=0.6.3",
]
